### ISSUE TITLE
error on status deamon

### ISSUE THREAD

**Issue by jualfoar** [mKeRix/ansible-playbooks#5]
Hi, i just install this program.
i got this error as status :  OmronD6tService: Retrieving the state from D6T sensor failed: ENOENT: no such file or direc.....

any ideas??

AND 
what will be the ideal distance between the differents RASPI?

thanks

**Comment by mKeRix** [comment]
You need to enable i2c for the Pis that you want to use with D6T or Grid-EYE, the playbook doesn't do this automatically (yet). Just log into the Pis via SSH and use `sudo raspi-config`, it's part of the Advanced Options if I remember correctly.

And there's no ideal distance really, it depends heavily on the surroundings, devices and configs. If there are no walls in-between you'll need at least 5m between Pis to get something valuable through Bluetooth I think, best is to have walls or other obstructions in-between. For thermopiles you can reach up to 5m in sensing distance depending on your surroundings, more realistically if you want to be sure there are no false triggers you should calculate with 3m.

**Comment by jualfoar** [comment]
Thanks for your answer. 
Do we really need a sensor on the gpio to this to work?? 

is there a refresh  time to check for devices? What is this time? Or this is why we need the pir sensor? 

Just because I have two raspi configured. I don’t have any pir sensors on them. There is a distance between them of 5.5m without walls. I could see on my home assistant that’s detects my phone on my slave raspi. When I disable it to see if it will be detected by the other Pi, nothing happen.

I don’t get any new values. And the other Pi never detects my phone. 

Thanks again.

**Comment by mKeRix** [comment]
If you want to use the d6t or the gridEye integrations you need to have the respective sensors hooked up - otherwise there is no way to measure the heat matrix. If you do not intend to use either of these sensors (e.g. if you just want to track Bluetooth devices) you do not need these integrations - double check your config to load the correct integrations!

Check the logs on the Pi that doesn't detect your device for what's loaded and what's happening. Make sure the device addresses are included in the configs of all room-assistant instances. Also make sure that you don't have a quorum or something like that setup. You can also try re-running the `setcap` commands mentioned [here](https://www.room-assistant.io/integrations/bluetooth-classic.html#requirements) on the Pi that doesn't work, then restart. It's easier to help with verbose logs of the instance that doesn't detect your phone - turn off the room-assistant service (`sudo systemctl stop room-assistant`) and run `room-assistant -v` from the `~/room-assistant` folder. (note that these instructions assume you installed via ansible)

**Comment by jualfoar** [comment]
Thank so much for your answer and help.
